/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package familycinema;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author a s u s
 */
public class admin extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;

    /**
     * Creates new form admin
     */
    crud aa = new crud();
    public admin() {
        initComponents();
        tampil_database();
        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_bioskop = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        txt_waktu = new javax.swing.JTextField();
        txt_idfilm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_studio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_jadwal = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_idjadwal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        bt_refresh = new javax.swing.JButton();
        bt_showtime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FAMILY CINEMA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setText("SCHEDULE MANAGER");

        tabel_bioskop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Film", "Judul"
            }
        ));
        jScrollPane1.setViewportView(tabel_bioskop);

        jLabel1.setText("Daftar Film");

        txt_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggalActionPerformed(evt);
            }
        });

        txt_idfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idfilmActionPerformed(evt);
            }
        });

        jLabel4.setText("Id Film");

        jLabel5.setText("Tanggal");

        jLabel6.setText("Waktu");

        jLabel7.setText("Studio");

        jLabel8.setText("Jadwal");

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_simpan.setMnemonic('S');
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        tabel_jadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Jadwal", "ID Film", "Tanggal", "Waktu", "Studio"
            }
        ));
        tabel_jadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_jadwalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_jadwal);

        jLabel9.setText("Daftar Jadwal");

        txt_idjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idjadwalActionPerformed(evt);
            }
        });

        jLabel10.setText("Id Jadwal");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*Id Jadwal tidak perlu diisi saat menambah jadwal");

        bt_back.setBackground(new java.awt.Color(204, 0, 0));
        bt_back.setForeground(new java.awt.Color(255, 255, 255));
        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        bt_refresh.setBackground(new java.awt.Color(51, 51, 255));
        bt_refresh.setForeground(new java.awt.Color(255, 255, 255));
        bt_refresh.setText("Refresh Jadwal");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        bt_showtime.setBackground(new java.awt.Color(0, 153, 0));
        bt_showtime.setForeground(new java.awt.Color(255, 255, 255));
        bt_showtime.setText("Show Manager");
        bt_showtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_showtimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(150, 150, 150))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_back)
                        .addGap(155, 155, 155)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_showtime)
                        .addGap(9, 9, 9))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_studio, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_idfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(22, 22, 22)
                                .addComponent(txt_tanggal))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_idjadwal)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset)
                        .addGap(27, 27, 27)
                        .addComponent(btn_ubah)
                        .addGap(27, 27, 27)
                        .addComponent(btn_hapus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(187, 187, 187)
                        .addComponent(bt_refresh)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_showtime)
                            .addComponent(bt_back))))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txt_idjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_idfilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_reset)
                    .addComponent(btn_ubah)
                    .addComponent(btn_hapus))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bt_refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalActionPerformed

    private void txt_idfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idfilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idfilmActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if (txt_idjadwal.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Maaf, ID jadwal belum diisi!");
            txt_idjadwal.requestFocus();
        } else {
            if (JOptionPane.showConfirmDialog (null, "Apakah anda yakin menghapus jadwal ini?","Warning",2) == JOptionPane.YES_OPTION) {
                String id = "";
                try {
                    aa.setId_jadwal(txt_idjadwal.getText());
                    aa.hapusJadwal(aa.getId_jadwal());

                    JOptionPane.showMessageDialog(null,"Data berhasil di hapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,"Data gagal di hapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
         if (txt_idjadwal.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Maaf, ID Jadwal belum diisi!");
        txt_idjadwal.requestFocus();
    } else if (txt_idfilm.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Maaf, ID Film belum diisi!");
        txt_idfilm.requestFocus();
    } else if (txt_tanggal.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Maaf, Tanggal belum diisi!");
        txt_tanggal.requestFocus();
    } else if (txt_waktu.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Maaf, Waktu belum diisi!");
        txt_waktu.requestFocus();
    } else if (txt_studio.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Maaf, Studio belum diisi!");
        txt_studio.requestFocus();
    } else {
        try {
            aa.setId_jadwal(txt_idjadwal.getText());
            int filmId = Integer.parseInt(txt_idfilm.getText()); // Konversi teks menjadi int
            aa.setFilmId(filmId);
            aa.setTanggal(txt_tanggal.getText());
            aa.setWaktu(txt_waktu.getText());
            aa.setStudio(txt_studio.getText());
            aa.ubahJadwal(txt_idjadwal.getText(), filmId, txt_tanggal.getText(), txt_waktu.getText(), txt_studio.getText());

            JOptionPane.showMessageDialog(null, "Jadwal berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampil_database();
            reset_text();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID Film harus berupa angka", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            txt_idfilm.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Jadwal gagal diubah", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (!txt_idjadwal.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"ID Jadwal tidak perlu diisi");
            txt_idfilm.requestFocus();
        } else if (txt_tanggal.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Maaf, tanggal belum diisi!");
            txt_tanggal.requestFocus();
        } else if (txt_waktu.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Maaf, waktu belum diisi!");
            txt_waktu.requestFocus();
        }
        else if (txt_studio.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Maaf, studi belum diisi!");
            txt_studio.requestFocus();
        }else {
            try {
                int filmId = Integer.parseInt(txt_idfilm.getText()); // Konversi teks menjadi int
                aa.setFilmId(filmId);
                aa.setTanggal(txt_tanggal.getText());
                aa.setWaktu(txt_waktu.getText());
                aa.setStudio(txt_studio.getText());
                aa.simpanJadwal(String.valueOf(aa.getFilmId()), aa.getTanggal(), aa.getWaktu(), aa.getStudio());
                
                JOptionPane.showMessageDialog(null,"Jadwal berhasil tersimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"Jadwal gagal tersimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tabel_jadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_jadwalMouseClicked
        // TODO add your handling code here:
        try {
            int row = tabel_jadwal.rowAtPoint(evt.getPoint());
            
            String id_jadwal = tabel_jadwal.getValueAt(row, 0).toString();
            String id_film = tabel_jadwal.getValueAt(row, 1).toString();
            String tanggal = tabel_jadwal.getValueAt(row, 2).toString();
            String waktu = tabel_jadwal.getValueAt(row, 3).toString();
            String studio = tabel_jadwal.getValueAt(row, 4).toString();
            
            txt_idjadwal.setText(String.valueOf(id_jadwal));
            txt_idfilm.setText(String.valueOf(id_film));
            txt_tanggal.setText(String.valueOf(tanggal));
            txt_waktu.setText(String.valueOf(waktu));
            txt_studio.setText(String.valueOf(studio));
            
        } catch (Exception e){
        }
    }//GEN-LAST:event_tabel_jadwalMouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_idjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idjadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idjadwalActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_backActionPerformed

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        // TODO add your handling code here:
        new admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void bt_showtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_showtimeActionPerformed
        // TODO add your handling code here:
        new showtimeManager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_showtimeActionPerformed

    public void tampil_database() {
        Object[] baris = {"Id Film", "Judul"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_bioskop.setModel(tabmode);
        try {
            hasil = aa.dataFilm();
            while (hasil.next()) {
                aa.setFilmId(hasil.getInt("id_film")); // Pastikan nama kolom benar
                aa.setJudul(hasil.getString("judul")); // Pastikan nama kolom benar
                String[] data = {String.valueOf(aa.getFilmId()), aa.getJudul()};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void tampil_data() {
        Object[] baris = {"Id Jadwal", "Id Film", "Tanggal", "Waktu", "Studio"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_jadwal.setModel(tabmode);
        try {
            hasil = aa.dataJadwal();
            while (hasil.next()) {
                aa.setId_jadwal(hasil.getString("id_jadwal")); // Pastikan nama kolom benar
                aa.setFilmId(hasil.getInt("id_film")); // Pastikan nama kolom benar
                aa.setTanggal(hasil.getString("tanggal")); // Pastikan nama kolom benar
                aa.setWaktu(hasil.getString("waktu")); // Pastikan nama kolom benar
                aa.setStudio(hasil.getString("studio")); // Pastikan nama kolom benar
                String[] data = {aa.getId_jadwal(), String.valueOf(aa.getFilmId()), aa.getTanggal(), aa.getWaktu(), aa.getStudio()};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void reset_text() {
        txt_idjadwal.setText("");
        txt_idfilm.setText("");
        txt_tanggal.setText("");
        txt_waktu.setText("");
        txt_studio.setText("");
    }

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_showtime;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_bioskop;
    private javax.swing.JTable tabel_jadwal;
    private javax.swing.JTextField txt_idfilm;
    private javax.swing.JTextField txt_idjadwal;
    private javax.swing.JTextField txt_studio;
    private javax.swing.JTextField txt_tanggal;
    private javax.swing.JTextField txt_waktu;
    // End of variables declaration//GEN-END:variables
}
